name: Build & Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build the workspace
        run: cargo build --verbose
      - name: Test the workspace
        run: cargo test --verbose
      - name: Check for up-to-date readme
        run: |
          ./update-readme.sh
          if [ ! -z "$(git status --untracked-files=no --porcelain)" ]; then
            echo "::warning::$(git status --untracked-files=no --porcelain)"
            echo "::error title=Changed files::There are changed files in the repository. Readme not up to date?"
            exit 1
          fi
